


SELECT * FROM customer LIMIT 20 
-- what is the total revenue generated by male vs female customers?
select gender,sum(purchase_amount)as revenue
from cutomer
group by gender
--
ALTER TABLE old_table_name RENAME TO new_table_name;

-- which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from customer)

--which are the top 5 products  with the highest average review rating ?
SELECT item_purchased,ROUND(AVG(review_rating),2) as "Average Rating"
from customer
group by item_purchased
order by avg(review_rating)DESC
LIMIT 5

-- compare the average purchase amount between standard and express shipping
--Whenever you see words like:
--compare
--category-wise
--department-wise
--for each
--per
--👉 Think GROUP BY.
 select shipping_type,ROUND(avg(purchase_amount),2)
 from customer
 where shipping_type in ('Standard','Express')
 group by shipping_type

--Do subscribed customers spend more? compare average spend and total revenue between subscribers and non- subscribers
Select subscription_status,
count(customer_id)as total_customers,
ROUND(avg(purchase_amount),2)as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;

-- which 5 products have the highest % of purchases with discounts applied?
SELECT item_purchased,
ROUND(100* SUM(CASE when discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;
-- segment customers into new,returning,and,loyal based on their total
-- number of previous purchases,and show the count of each segment.
with customer_type as( 
select customer_id,previous_purchases,
case
    when previous_purchases=1 then 'New'
	when previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    else 'Loyal'
    END AS customer_segment
from customer
)
select customer_segment,count(*) as "number of customers"
from customer_type
group by customer_segment

-- what are the top 3 most purchased products within each category?
with item_counts as (
select item_purchased,category,
COUNT(customer_id)as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id)DESC)as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3

-- are the customers who are repeat buyers(more than5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from cutomer
where previous_purchases>=5
group by subscription_status

-- what is the revenue controbution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;





 









